Added display Initialization Function
NDSUFormulaE/Inverter-Controller pull request #24
Opened 2021-11-04 23:15 UTC by Shad0w-Dragon

-Implements TM1637TinyDisplay library
-Plays Startup Animation, then
-Sets all displays to their zero values

2021-11-17 18:23 UTC, brennancoslett requested changes
Can you add functions for updating each of the displays that can be called elsewhere?

That way only the gpioHandler cares about the which display is which

2021-11-17 18:23 UTC, brennancoslett commented on InverterApp/src/gpioHandler/gpioHandler.h
> +#define SPD_DISPLAY_CLK 0
Can you define all of the PINS like this?

Something like
```suggestion
## Speed Display Pins
#define SPD_CLK 0
#define SPD_DATA 1

## Coolant Temp Pins
#define Coolant_Clk 2
#define Coolant_Data 3

...
```

2021-11-17 18:23 UTC, brennancoslett commented on InverterApp/src/gpioHandler/gpioHandler.cpp
> +        // ALL OF OUR CODE
remove this comment

2021-12-02 23:43 UTC, Shad0w-Dragon commented
Defined display pins in gpioHandler.h

2021-12-09 23:52 UTC, brennancoslett approved these changes

2021-12-09 23:53 UTC, merged